filebeat.inputs:
- type: filestream
  enabled: true
  parsers:
    - multiline:
        type: pattern
        pattern: '^[[:space:]]Event:'
        negate: false
        match: after
  include_lines: ['Event:']
  paths:
   - <IS_HOME>/repository/logs/wso2carbon*.log
   - <IS_HOME>/repository/logs/audit*.log
filebeat.registry.path: ./registry
output.logstash:
  hosts: ["localhost:5044"]

